name: biobb_AMBER_MDsetup_tutorials
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_analysis==4.1.0
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_chemistry==4.1.0
  - biobb_amber==4.1.0
  - jupyter_client==7.3.2
  - gfortran==11.3.0
  - libgfortran5==11.3.0
  - nb_conda_kernels
  - traitlets==5.9.0
  - jupyter_contrib_nbextensions
  - plotly
  - nglview
  - simpletraj
  - conda
